//! The table designer's model: a table as loaded from the catalog, the same
//! table as edited, and the DDL that turns one into the other.
//!
//! Columns and indexes carry a stable `id`, so a rename is a rename and not a
//! drop plus an add. Everything here is plain data and SQL text; the window
//! lives in `designer/mod.rs`.

use std::collections::BTreeSet;

use sqail_client::proto::{ColumnInfo, Engine, ForeignKeyInfo, IndexInfo, TableGrant};

use crate::sql::{qualified_name, quote_ident};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Column {
    pub id: u64,
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    /// Default expression as SQL text; empty for none.
    pub default: String,
}

/// One key of an index: a column, or an expression kept as the catalog gave it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IndexPart {
    Column(u64),
    Expr(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Index {
    pub id: u64,
    pub name: String,
    pub parts: Vec<IndexPart>,
    pub unique: bool,
    /// Backs a `UNIQUE` constraint (dropped and re-added as a constraint).
    pub constraint: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PrimaryKey {
    /// Constraint name; empty lets the database choose.
    pub name: String,
    /// Column ids in key order; empty for no primary key.
    pub columns: Vec<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Table {
    pub schema: String,
    pub name: String,
    pub columns: Vec<Column>,
    pub primary_key: PrimaryKey,
    pub indexes: Vec<Index>,
    /// (grantee, privilege)
    pub grants: BTreeSet<(String, String)>,
}

/// What the designer shows for a column.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    New,
    Changed,
    Same,
}

/// The statements that apply a design, in order.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Plan {
    /// Run before the transaction (SQLite: switch foreign keys off).
    pub pre: Vec<String>,
    /// Run in one transaction.
    pub body: Vec<String>,
    /// A query that must return no rows before COMMIT.
    pub check: Option<String>,
    /// Run after the transaction, whatever its outcome.
    pub post: Vec<String>,
    pub warnings: Vec<String>,
}

impl Plan {
    pub fn is_empty(&self) -> bool {
        self.body.is_empty()
    }

    /// The whole plan as a script, for review and "open in editor".
    pub fn script(&self, engine: Engine) -> String {
        let begin = if engine == Engine::Mssql {
            "BEGIN TRANSACTION"
        } else {
            "BEGIN"
        };
        let mut lines: Vec<String> = self.pre.clone();
        lines.push(begin.into());
        lines.extend(self.body.iter().cloned());
        if let Some(c) = &self.check {
            lines.push(format!("{c} -- must return no rows"));
        }
        lines.push("COMMIT".into());
        lines.extend(self.post.iter().cloned());
        lines
            .iter()
            .map(|l| format!("{l};"))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Privileges offered as checkboxes on the security page.
pub fn privileges(engine: Engine) -> &'static [&'static str] {
    match engine {
        Engine::Postgres => &[
            "SELECT",
            "INSERT",
            "UPDATE",
            "DELETE",
            "TRUNCATE",
            "REFERENCES",
            "TRIGGER",
        ],
        Engine::Mssql => &[
            "SELECT",
            "INSERT",
            "UPDATE",
            "DELETE",
            "REFERENCES",
            "ALTER",
            "CONTROL",
            "VIEW DEFINITION",
        ],
        Engine::Sqlite => &[],
    }
}

/// Common type names offered next to the type field.
pub fn type_suggestions(engine: Engine) -> &'static [&'static str] {
    match engine {
        Engine::Postgres => &[
            "integer",
            "bigint",
            "smallint",
            "bigint GENERATED BY DEFAULT AS IDENTITY",
            "numeric(18,2)",
            "real",
            "double precision",
            "boolean",
            "text",
            "varchar(255)",
            "char(1)",
            "date",
            "time",
            "timestamp",
            "timestamptz",
            "uuid",
            "jsonb",
            "bytea",
        ],
        Engine::Mssql => &[
            "int",
            "bigint",
            "smallint",
            "tinyint",
            "int IDENTITY(1,1)",
            "decimal(18,2)",
            "float",
            "bit",
            "nvarchar(255)",
            "nvarchar(max)",
            "varchar(255)",
            "nchar(1)",
            "date",
            "time(7)",
            "datetime2(7)",
            "datetimeoffset(7)",
            "uniqueidentifier",
            "varbinary(max)",
        ],
        Engine::Sqlite => &["INTEGER", "REAL", "NUMERIC", "TEXT", "BLOB"],
    }
}

fn default_schema(engine: Engine) -> &'static str {
    match engine {
        Engine::Postgres => "public",
        Engine::Mssql => "dbo",
        Engine::Sqlite => "main",
    }
}

/// A `N'…'` / `'…'` string literal.
fn lit(engine: Engine, s: &str) -> String {
    let q = format!("'{}'", s.replace('\'', "''"));
    if engine == Engine::Mssql {
        format!("N{q}")
    } else {
        q
    }
}

/// SQLite's `ALTER TABLE … ADD COLUMN` takes only constant defaults, and a
/// `CREATE TABLE` default that is an expression needs parentheses.
fn sqlite_constant(d: &str) -> bool {
    let d = d.trim();
    let upper = d.to_ascii_uppercase();
    d.parse::<f64>().is_ok()
        || (d.starts_with('\'') && d.ends_with('\'') && d.len() >= 2)
        || ((upper.starts_with("X'")) && d.ends_with('\''))
        || matches!(upper.as_str(), "NULL" | "TRUE" | "FALSE")
}

fn sqlite_default(d: &str) -> String {
    let d = d.trim();
    let upper = d.to_ascii_uppercase();
    if sqlite_constant(d)
        || d.starts_with('(')
        || matches!(
            upper.as_str(),
            "CURRENT_TIME" | "CURRENT_DATE" | "CURRENT_TIMESTAMP"
        )
    {
        d.to_string()
    } else {
        format!("({d})")
    }
}

/// A table being designed: the catalog's version and the edited one.
#[derive(Debug, Clone)]
pub struct Design {
    pub engine: Engine,
    /// `None` for a table that does not exist yet.
    pub original: Option<Table>,
    pub table: Table,
    /// Kept so an SQLite rebuild can re-create them.
    pub foreign_keys: Vec<ForeignKeyInfo>,
    /// Grants held `WITH GRANT OPTION`; revoking them needs `CASCADE`.
    pub grantable: BTreeSet<(String, String)>,
    next_id: u64,
}

impl Design {
    /// A new table with an `id` primary key.
    pub fn new_table(engine: Engine, schema: Option<&str>) -> Self {
        let id_type = match engine {
            Engine::Postgres => "integer",
            Engine::Mssql => "int",
            Engine::Sqlite => "INTEGER",
        };
        let mut d = Self {
            engine,
            original: None,
            table: Table {
                schema: schema.unwrap_or(default_schema(engine)).to_string(),
                ..Default::default()
            },
            foreign_keys: Vec::new(),
            grantable: BTreeSet::new(),
            next_id: 1,
        };
        let id = d.add_column();
        let c = d.column_mut(id).expect("just added");
        c.name = "id".into();
        c.data_type = id_type.into();
        d.toggle_pk(id);
        d
    }

    /// An existing table as the catalog describes it.
    pub fn from_catalog(
        engine: Engine,
        schema: &str,
        name: &str,
        columns: &[ColumnInfo],
        indexes: &[IndexInfo],
        foreign_keys: Vec<ForeignKeyInfo>,
        grants: &[TableGrant],
    ) -> Self {
        let mut next_id = 1;
        let mut id = || {
            let v = next_id;
            next_id += 1;
            v
        };
        let cols: Vec<Column> = columns
            .iter()
            .map(|c| Column {
                id: id(),
                name: c.name.clone(),
                data_type: c.data_type.clone(),
                nullable: c.nullable,
                default: c.default.clone().unwrap_or_default(),
            })
            .collect();
        let find = |key: &str| {
            cols.iter()
                .find(|c| c.name == key || quote_ident(engine, &c.name) == key)
                .map(|c| c.id)
        };
        let primary_key = match indexes.iter().find(|i| i.primary) {
            Some(pk) => PrimaryKey {
                // SQLite primary keys have no name of their own.
                name: if engine == Engine::Sqlite {
                    String::new()
                } else {
                    pk.name.clone()
                },
                columns: pk.columns.iter().filter_map(|c| find(c)).collect(),
            },
            // SQLite `INTEGER PRIMARY KEY` has no index.
            None => PrimaryKey {
                name: String::new(),
                columns: columns
                    .iter()
                    .zip(&cols)
                    .filter(|(ci, _)| ci.primary_key)
                    .map(|(_, c)| c.id)
                    .collect(),
            },
        };
        let indexes = indexes
            .iter()
            .filter(|i| !i.primary)
            .map(|i| Index {
                id: id(),
                name: i.name.clone(),
                parts: i
                    .columns
                    .iter()
                    .map(|k| match find(k) {
                        Some(c) => IndexPart::Column(c),
                        None => IndexPart::Expr(k.clone()),
                    })
                    .collect(),
                unique: i.unique,
                constraint: i.constraint,
            })
            .collect();
        let table = Table {
            schema: schema.to_string(),
            name: name.to_string(),
            columns: cols,
            primary_key,
            indexes,
            grants: grants
                .iter()
                .map(|g| (g.grantee.clone(), g.privilege.clone()))
                .collect(),
        };
        Self {
            engine,
            original: Some(table.clone()),
            table,
            foreign_keys,
            grantable: grants
                .iter()
                .filter(|g| g.grantable)
                .map(|g| (g.grantee.clone(), g.privilege.clone()))
                .collect(),
            next_id,
        }
    }

    pub fn is_new(&self) -> bool {
        self.original.is_none()
    }

    /// Throw away every edit.
    pub fn revert(&mut self) {
        if let Some(o) = &self.original {
            self.table = o.clone();
        }
    }

    fn fresh_id(&mut self) -> u64 {
        let v = self.next_id;
        self.next_id += 1;
        v
    }

    // ------------------------------------------------------------ columns --

    pub fn column(&self, id: u64) -> Option<&Column> {
        self.table.columns.iter().find(|c| c.id == id)
    }

    pub fn column_mut(&mut self, id: u64) -> Option<&mut Column> {
        self.table.columns.iter_mut().find(|c| c.id == id)
    }

    pub fn column_name(&self, id: u64) -> String {
        self.column(id).map(|c| c.name.clone()).unwrap_or_default()
    }

    fn original_column(&self, id: u64) -> Option<&Column> {
        self.original.as_ref()?.columns.iter().find(|c| c.id == id)
    }

    /// Append an empty nullable column; returns its id.
    pub fn add_column(&mut self) -> u64 {
        let id = self.fresh_id();
        let data_type = match self.engine {
            Engine::Postgres => "text",
            Engine::Mssql => "nvarchar(255)",
            Engine::Sqlite => "TEXT",
        };
        let n = self.table.columns.len() + 1;
        self.table.columns.push(Column {
            id,
            name: format!("column{n}"),
            data_type: data_type.into(),
            nullable: true,
            default: String::new(),
        });
        id
    }

    /// Remove a column, and with it its place in the key and in indexes.
    pub fn remove_column(&mut self, id: u64) {
        self.table.columns.retain(|c| c.id != id);
        self.table.primary_key.columns.retain(|c| *c != id);
        for i in &mut self.table.indexes {
            i.parts.retain(|p| *p != IndexPart::Column(id));
        }
        self.table.indexes.retain(|i| !i.parts.is_empty());
    }

    /// Columns of the loaded table that the design removed.
    pub fn removed_columns(&self) -> Vec<Column> {
        let Some(o) = &self.original else {
            return Vec::new();
        };
        o.columns
            .iter()
            .filter(|c| self.column(c.id).is_none())
            .cloned()
            .collect()
    }

    /// Bring a removed column back, as it was loaded.
    pub fn restore_column(&mut self, id: u64) {
        let Some(o) = &self.original else { return };
        let Some(pos) = o.columns.iter().position(|c| c.id == id) else {
            return;
        };
        let col = o.columns[pos].clone();
        // Before the first column that came after it in the loaded table.
        let at = o.columns[pos + 1..]
            .iter()
            .find_map(|next| self.table.columns.iter().position(|c| c.id == next.id))
            .unwrap_or(self.table.columns.len());
        self.table.columns.insert(at, col);
    }

    /// Move a column up (`-1`) or down (`+1`); new tables only.
    pub fn move_column(&mut self, id: u64, delta: isize) {
        let Some(i) = self.table.columns.iter().position(|c| c.id == id) else {
            return;
        };
        let j = i as isize + delta;
        if j >= 0 && (j as usize) < self.table.columns.len() {
            self.table.columns.swap(i, j as usize);
        }
    }

    pub fn column_status(&self, id: u64) -> Status {
        match (self.original_column(id), self.column(id)) {
            (None, _) if self.original.is_some() => Status::New,
            (Some(o), Some(c)) if o != c => Status::Changed,
            _ => Status::Same,
        }
    }

    // ---------------------------------------------------------------- key --

    pub fn in_pk(&self, id: u64) -> bool {
        self.table.primary_key.columns.contains(&id)
    }

    /// Add a column to the primary key (it becomes NOT NULL), or take it out.
    pub fn toggle_pk(&mut self, id: u64) {
        let pk = &mut self.table.primary_key.columns;
        if let Some(i) = pk.iter().position(|c| *c == id) {
            pk.remove(i);
        } else {
            pk.push(id);
            if let Some(c) = self.column_mut(id) {
                c.nullable = false;
            }
        }
    }

    pub fn move_pk_column(&mut self, pos: usize, delta: isize) {
        let pk = &mut self.table.primary_key.columns;
        let j = pos as isize + delta;
        if pos < pk.len() && j >= 0 && (j as usize) < pk.len() {
            pk.swap(pos, j as usize);
        }
    }

    // ------------------------------------------------------------ indexes --

    pub fn add_index(&mut self) -> u64 {
        let id = self.fresh_id();
        let base = if self.table.name.is_empty() {
            "table"
        } else {
            &self.table.name
        };
        let mut n = 1;
        let name = loop {
            let candidate = format!("ix_{base}_{n}");
            if !self.table.indexes.iter().any(|i| i.name == candidate) {
                break candidate;
            }
            n += 1;
        };
        self.table.indexes.push(Index {
            id,
            name,
            parts: Vec::new(),
            unique: false,
            constraint: false,
        });
        id
    }

    pub fn index_mut(&mut self, id: u64) -> Option<&mut Index> {
        self.table.indexes.iter_mut().find(|i| i.id == id)
    }

    pub fn remove_index(&mut self, id: u64) {
        self.table.indexes.retain(|i| i.id != id);
    }

    pub fn index_status(&self, idx: &Index) -> Status {
        match self
            .original
            .as_ref()
            .map(|o| o.indexes.iter().find(|i| i.id == idx.id))
        {
            Some(None) => Status::New,
            Some(Some(o)) if o != idx => Status::Changed,
            _ => Status::Same,
        }
    }

    pub fn part_label(&self, p: &IndexPart) -> String {
        match p {
            IndexPart::Column(id) => self.column_name(*id),
            IndexPart::Expr(e) => e.clone(),
        }
    }

    // ------------------------------------------------------------- grants --

    pub fn grantees(&self) -> Vec<String> {
        let mut g: Vec<String> = self
            .table
            .grants
            .iter()
            .map(|(who, _)| who.clone())
            .collect();
        g.dedup();
        g
    }

    pub fn has_grant(&self, grantee: &str, privilege: &str) -> bool {
        self.table
            .grants
            .contains(&(grantee.to_string(), privilege.to_string()))
    }

    pub fn set_grant(&mut self, grantee: &str, privilege: &str, on: bool) {
        let key = (grantee.to_string(), privilege.to_string());
        if on {
            self.table.grants.insert(key);
        } else {
            self.table.grants.remove(&key);
        }
    }

    pub fn revoke_all(&mut self, grantee: &str) {
        self.table.grants.retain(|(who, _)| who != grantee);
    }

    // ---------------------------------------------------------------- SQL --

    fn q(&self, s: &str) -> String {
        quote_ident(self.engine, s)
    }

    fn qualified(&self, name: &str) -> String {
        qualified_name(self.engine, Some(&self.table.schema), name)
    }

    /// An index name where the statement wants it schema-qualified.
    fn index_ref(&self, name: &str) -> String {
        match self.engine {
            Engine::Mssql => self.q(name),
            _ => self.qualified(name),
        }
    }

    fn column_def(&self, c: &Column) -> String {
        let mut s = format!("{} {}", self.q(&c.name), c.data_type.trim());
        match (self.engine, c.nullable) {
            (Engine::Mssql, true) => s.push_str(" NULL"),
            (_, false) => s.push_str(" NOT NULL"),
            _ => {}
        }
        let d = c.default.trim();
        if !d.is_empty() {
            let d = if self.engine == Engine::Sqlite {
                sqlite_default(d)
            } else {
                d.to_string()
            };
            s.push_str(&format!(" DEFAULT {d}"));
        }
        s
    }

    fn column_list(&self, ids: &[u64]) -> String {
        ids.iter()
            .map(|id| self.q(&self.column_name(*id)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn parts_sql(&self, parts: &[IndexPart]) -> String {
        parts
            .iter()
            .map(|p| match p {
                IndexPart::Column(id) => self.q(&self.column_name(*id)),
                IndexPart::Expr(e) => e.clone(),
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn pk_clause(&self) -> Option<String> {
        let pk = &self.table.primary_key;
        if pk.columns.is_empty() {
            return None;
        }
        let name = pk.name.trim();
        let named = if name.is_empty() || self.engine == Engine::Sqlite {
            String::new()
        } else {
            format!("CONSTRAINT {} ", self.q(name))
        };
        Some(format!(
            "{named}PRIMARY KEY ({})",
            self.column_list(&pk.columns)
        ))
    }

    /// A unique constraint can be written as one when it is only columns.
    fn unique_constraint(&self, i: &Index) -> bool {
        i.constraint && i.unique && i.parts.iter().all(|p| matches!(p, IndexPart::Column(_)))
    }

    fn create_index(&self, i: &Index, table: &str) -> String {
        if self.unique_constraint(i) && self.engine != Engine::Sqlite {
            format!(
                "ALTER TABLE {table} ADD CONSTRAINT {} UNIQUE ({})",
                self.q(&i.name),
                self.parts_sql(&i.parts)
            )
        } else {
            // SQLite puts the schema on the index name, not the table.
            let (name, on) = match self.engine {
                Engine::Sqlite => (
                    self.qualified(&i.name),
                    self.q(&self.table.name).to_string(),
                ),
                _ => (self.q(&i.name), table.to_string()),
            };
            format!(
                "CREATE {}INDEX {name} ON {on} ({})",
                if i.unique { "UNIQUE " } else { "" },
                self.parts_sql(&i.parts)
            )
        }
    }

    fn grantee(&self, g: &str) -> String {
        if self.engine == Engine::Postgres && g.eq_ignore_ascii_case("public") {
            "PUBLIC".into()
        } else {
            self.q(g)
        }
    }

    /// Problems that stop the design from being applied.
    pub fn problems(&self) -> Vec<String> {
        let t = &self.table;
        let mut out = Vec::new();
        if t.name.trim().is_empty() {
            out.push("The table needs a name.".to_string());
        }
        if t.columns.is_empty() {
            out.push("A table needs at least one column.".into());
        }
        let mut seen = BTreeSet::new();
        for c in &t.columns {
            if c.name.trim().is_empty() {
                out.push("Every column needs a name.".into());
            } else if !seen.insert(c.name.to_lowercase()) {
                out.push(format!("Column “{}” appears twice.", c.name));
            }
            if c.data_type.trim().is_empty() {
                out.push(format!("Column “{}” needs a type.", c.name));
            }
        }
        let mut seen = BTreeSet::new();
        for i in &t.indexes {
            if i.name.trim().is_empty() {
                out.push("Every index needs a name.".into());
            } else if !seen.insert(i.name.to_lowercase()) {
                out.push(format!("Index “{}” appears twice.", i.name));
            }
            if i.parts.is_empty() {
                out.push(format!("Index “{}” has no columns.", i.name));
            }
        }
        if !t.grants.is_empty() && self.engine == Engine::Sqlite {
            out.push("SQLite has no table privileges.".into());
        }
        if t.grants.iter().any(|(g, _)| g.trim().is_empty()) {
            out.push("A grant needs a role or user.".into());
        }
        out
    }

    /// The statements that apply the design, or what stops it.
    pub fn plan(&self) -> Result<Plan, Vec<String>> {
        let problems = self.problems();
        if !problems.is_empty() {
            return Err(problems);
        }
        Ok(match &self.original {
            None => self.create_plan(),
            Some(o) if self.engine == Engine::Sqlite && self.sqlite_needs_rebuild(o) => {
                self.rebuild_plan(o)
            }
            Some(o) => self.alter_plan(o),
        })
    }

    fn create_body(&self, name: &str) -> String {
        let mut lines: Vec<String> = self
            .table
            .columns
            .iter()
            .map(|c| format!("    {}", self.column_def(c)))
            .collect();
        lines.extend(self.pk_clause().map(|pk| format!("    {pk}")));
        format!("CREATE TABLE {name} (\n{}\n)", lines.join(",\n"))
    }

    fn grant_statements(&self, from: &BTreeSet<(String, String)>, table: &str) -> Vec<String> {
        let mut out = Vec::new();
        for (who, p) in from.difference(&self.table.grants) {
            let cascade = if self.grantable.contains(&(who.clone(), p.clone())) {
                " CASCADE"
            } else {
                ""
            };
            out.push(format!(
                "REVOKE {p} ON {table} FROM {}{cascade}",
                self.grantee(who)
            ));
        }
        for (who, p) in self.table.grants.difference(from) {
            out.push(format!("GRANT {p} ON {table} TO {}", self.grantee(who)));
        }
        out
    }

    fn create_plan(&self) -> Plan {
        let table = self.qualified(&self.table.name);
        let mut body = vec![self.create_body(&table)];
        for i in &self.table.indexes {
            body.push(self.create_index(i, &table));
        }
        body.extend(self.grant_statements(&BTreeSet::new(), &table));
        Plan {
            body,
            ..Default::default()
        }
    }

    /// Columns whose type or nullability changes (SQL Server then needs the
    /// indexes and key on them dropped and re-created).
    fn retyped(&self, o: &Table) -> BTreeSet<u64> {
        o.columns
            .iter()
            .filter_map(|oc| {
                let c = self.column(oc.id)?;
                (c.data_type.trim() != oc.data_type.trim() || c.nullable != oc.nullable)
                    .then_some(oc.id)
            })
            .collect()
    }

    fn alter_plan(&self, o: &Table) -> Plan {
        let e = self.engine;
        let t = &self.table;
        let mut body = Vec::new();
        let mut table = self.qualified(&o.name);

        // Rename the table first; everything after uses the new name.
        if t.name != o.name {
            body.push(match e {
                Engine::Mssql => format!("EXEC sp_rename {}, {}", lit(e, &table), lit(e, &t.name)),
                _ => format!("ALTER TABLE {table} RENAME TO {}", self.q(&t.name)),
            });
            table = self.qualified(&t.name);
        }

        let revokes: Vec<String> = self
            .grant_statements(&o.grants, &table)
            .into_iter()
            .filter(|s| s.starts_with("REVOKE"))
            .collect();
        body.extend(revokes);

        let retyped = if e == Engine::Mssql {
            self.retyped(o)
        } else {
            BTreeSet::new()
        };
        let touches_retyped = |parts: &[IndexPart]| {
            parts
                .iter()
                .any(|p| matches!(p, IndexPart::Column(c) if retyped.contains(c)))
        };

        // Indexes that go away or change are dropped before columns change.
        let mut recreate: Vec<&Index> = Vec::new();
        let mut renames: Vec<(&Index, &Index)> = Vec::new();
        for oi in &o.indexes {
            let ni = t.indexes.iter().find(|i| i.id == oi.id);
            let same_shape = ni.is_some_and(|ni| {
                ni.parts == oi.parts && ni.unique == oi.unique && !touches_retyped(&ni.parts)
            });
            if let (Some(ni), true) = (ni, same_shape) {
                if ni.name != oi.name {
                    if e == Engine::Sqlite {
                        recreate.push(ni);
                    } else {
                        renames.push((oi, ni));
                        continue;
                    }
                } else {
                    continue;
                }
            }
            body.push(if oi.constraint && e != Engine::Sqlite {
                format!("ALTER TABLE {table} DROP CONSTRAINT {}", self.q(&oi.name))
            } else if e == Engine::Mssql {
                format!("DROP INDEX {} ON {table}", self.q(&oi.name))
            } else {
                format!("DROP INDEX {}", self.index_ref(&oi.name))
            });
            if let Some(ni) = ni
                && !recreate.iter().any(|r| r.id == ni.id)
            {
                recreate.push(ni);
            }
        }
        for ni in &t.indexes {
            if !o.indexes.iter().any(|i| i.id == ni.id) {
                recreate.push(ni);
            }
        }

        // The primary key.
        let (opk, npk) = (&o.primary_key, &t.primary_key);
        let pk_rebuilt = opk.columns != npk.columns || touches_retyped_ids(&retyped, &npk.columns);
        if pk_rebuilt && !opk.columns.is_empty() {
            body.push(format!(
                "ALTER TABLE {table} DROP CONSTRAINT {}",
                self.q(&opk.name)
            ));
        }

        // SQL Server: a default constraint blocks dropping or retyping its
        // column; drop it by its (generated) name and add it back later.
        let mut readd_default: Vec<&Column> = Vec::new();
        if e == Engine::Mssql {
            for oc in &o.columns {
                if oc.default.trim().is_empty() {
                    continue;
                }
                let nc = self.column(oc.id);
                let drop = match nc {
                    None => true,
                    Some(nc) => nc.default.trim() != oc.default.trim() || retyped.contains(&oc.id),
                };
                if drop {
                    body.push(format!(
                        "DECLARE @df sysname = (SELECT d.name FROM sys.default_constraints d \
                         JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id \
                         WHERE d.parent_object_id = OBJECT_ID({}) AND c.name = {});\n\
                         DECLARE @drop nvarchar(max) = {} + QUOTENAME(@df);\n\
                         IF @df IS NOT NULL EXEC sp_executesql @drop",
                        lit(e, &table),
                        lit(e, &oc.name),
                        lit(e, &format!("ALTER TABLE {table} DROP CONSTRAINT "))
                    ));
                    if let Some(nc) = nc
                        && !nc.default.trim().is_empty()
                    {
                        readd_default.push(nc);
                    }
                }
            }
            for oc in &o.columns {
                if let Some(nc) = self.column(oc.id)
                    && oc.default.trim().is_empty()
                    && !nc.default.trim().is_empty()
                {
                    readd_default.push(nc);
                }
            }
        }

        // Columns: drop, rename, alter, add.
        for oc in &o.columns {
            if self.column(oc.id).is_none() {
                body.push(format!(
                    "ALTER TABLE {table} DROP COLUMN {}",
                    self.q(&oc.name)
                ));
            }
        }
        for oc in &o.columns {
            let Some(nc) = self.column(oc.id) else {
                continue;
            };
            if nc.name != oc.name {
                body.push(match e {
                    Engine::Mssql => format!(
                        "EXEC sp_rename {}, {}, N'COLUMN'",
                        lit(e, &format!("{table}.{}", self.q(&oc.name))),
                        lit(e, &nc.name)
                    ),
                    _ => format!(
                        "ALTER TABLE {table} RENAME COLUMN {} TO {}",
                        self.q(&oc.name),
                        self.q(&nc.name)
                    ),
                });
            }
        }
        for oc in &o.columns {
            let Some(nc) = self.column(oc.id) else {
                continue;
            };
            let col = self.q(&nc.name);
            let ty = nc.data_type.trim();
            let type_changed = ty != oc.data_type.trim();
            match e {
                Engine::Postgres => {
                    if type_changed {
                        body.push(format!(
                            "ALTER TABLE {table} ALTER COLUMN {col} TYPE {ty} USING {col}::{ty}"
                        ));
                    }
                    if nc.nullable != oc.nullable {
                        let what = if nc.nullable { "DROP" } else { "SET" };
                        body.push(format!(
                            "ALTER TABLE {table} ALTER COLUMN {col} {what} NOT NULL"
                        ));
                    }
                    if nc.default.trim() != oc.default.trim() {
                        body.push(if nc.default.trim().is_empty() {
                            format!("ALTER TABLE {table} ALTER COLUMN {col} DROP DEFAULT")
                        } else {
                            format!(
                                "ALTER TABLE {table} ALTER COLUMN {col} SET DEFAULT {}",
                                nc.default.trim()
                            )
                        });
                    }
                }
                Engine::Mssql => {
                    if type_changed || nc.nullable != oc.nullable {
                        let null = if nc.nullable { "NULL" } else { "NOT NULL" };
                        body.push(format!(
                            "ALTER TABLE {table} ALTER COLUMN {col} {ty} {null}"
                        ));
                    }
                }
                Engine::Sqlite => {} // changes like these rebuild the table
            }
        }
        for c in &t.columns {
            if o.columns.iter().any(|oc| oc.id == c.id) {
                continue;
            }
            let add = if e == Engine::Postgres || e == Engine::Sqlite {
                "ADD COLUMN"
            } else {
                "ADD"
            };
            body.push(format!("ALTER TABLE {table} {add} {}", self.column_def(c)));
        }
        for c in readd_default {
            body.push(format!(
                "ALTER TABLE {table} ADD DEFAULT {} FOR {}",
                c.default.trim(),
                self.q(&c.name)
            ));
        }

        if pk_rebuilt {
            if let Some(pk) = self.pk_clause() {
                body.push(format!("ALTER TABLE {table} ADD {pk}"));
            }
        } else if !npk.columns.is_empty()
            && !npk.name.trim().is_empty()
            && npk.name != opk.name
            && e != Engine::Sqlite
        {
            body.push(match e {
                Engine::Mssql => format!(
                    "EXEC sp_rename {}, {}, N'OBJECT'",
                    lit(e, &self.qualified(&opk.name)),
                    lit(e, npk.name.trim())
                ),
                _ => format!(
                    "ALTER TABLE {table} RENAME CONSTRAINT {} TO {}",
                    self.q(&opk.name),
                    self.q(npk.name.trim())
                ),
            });
        }

        for (oi, ni) in renames {
            body.push(match e {
                Engine::Mssql => format!(
                    "EXEC sp_rename {}, {}, N'INDEX'",
                    lit(e, &format!("{table}.{}", self.q(&oi.name))),
                    lit(e, &ni.name)
                ),
                _ => format!(
                    "ALTER INDEX {} RENAME TO {}",
                    self.index_ref(&oi.name),
                    self.q(&ni.name)
                ),
            });
        }
        for i in recreate {
            body.push(self.create_index(i, &table));
        }

        let grants: Vec<String> = self
            .grant_statements(&o.grants, &table)
            .into_iter()
            .filter(|s| s.starts_with("GRANT"))
            .collect();
        body.extend(grants);

        let mut warnings = Vec::new();
        if e == Engine::Postgres && body.iter().any(|s| s.contains(" TYPE ")) {
            warnings.push(
                "Changing a column type rewrites the table and fails if a value cannot be converted."
                    .into(),
            );
        }
        if !self.removed_columns().is_empty() {
            warnings.push("Dropped columns and their data cannot be recovered.".into());
        }
        Plan {
            body,
            warnings,
            ..Default::default()
        }
    }

    /// SQLite alters in place only renames, plain added columns, dropped
    /// columns and ordinary indexes; everything else rebuilds the table.
    fn sqlite_needs_rebuild(&self, o: &Table) -> bool {
        let t = &self.table;
        let changed = o.columns.iter().any(|oc| {
            self.column(oc.id).is_some_and(|c| {
                c.data_type.trim() != oc.data_type.trim()
                    || c.nullable != oc.nullable
                    || c.default.trim() != oc.default.trim()
            })
        });
        let pk_changed = o.primary_key.columns != t.primary_key.columns;
        let hard_add = t
            .columns
            .iter()
            .filter(|c| !o.columns.iter().any(|oc| oc.id == c.id))
            .any(|c| {
                let d = c.default.trim();
                self.in_pk(c.id)
                    || (!c.nullable && d.is_empty())
                    || (!d.is_empty() && !sqlite_constant(d))
            });
        let fk_columns: BTreeSet<&str> = self
            .foreign_keys
            .iter()
            .flat_map(|f| f.columns.iter().map(String::as_str))
            .collect();
        let hard_drop = self
            .removed_columns()
            .iter()
            .any(|c| fk_columns.contains(c.name.as_str()));
        let constraint_changed = o
            .indexes
            .iter()
            .filter(|i| i.constraint)
            .any(|oi| t.indexes.iter().find(|i| i.id == oi.id) != Some(oi));
        changed || pk_changed || hard_add || hard_drop || constraint_changed
    }

    fn rebuild_plan(&self, o: &Table) -> Plan {
        let t = &self.table;
        let old = self.qualified(&o.name);
        let tmp_name = format!("_sqail_new_{}", t.name);
        let tmp = self.qualified(&tmp_name);

        let mut create = self.create_body(&tmp);
        // Unique constraints and surviving foreign keys go into the new table.
        let mut extra = Vec::new();
        for i in t.indexes.iter().filter(|i| self.unique_constraint(i)) {
            extra.push(format!("    UNIQUE ({})", self.parts_sql(&i.parts)));
        }
        for fk in &self.foreign_keys {
            let ids: Option<Vec<u64>> = fk
                .columns
                .iter()
                .map(|n| {
                    o.columns
                        .iter()
                        .find(|c| &c.name == n)
                        .map(|c| c.id)
                        .filter(|id| self.column(*id).is_some())
                })
                .collect();
            let Some(ids) = ids else { continue };
            let refs = if fk.ref_columns.is_empty() {
                String::new()
            } else {
                format!(
                    " ({})",
                    fk.ref_columns
                        .iter()
                        .map(|c| self.q(c))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            };
            extra.push(format!(
                "    FOREIGN KEY ({}) REFERENCES {}{refs}",
                self.column_list(&ids),
                self.q(&fk.ref_table)
            ));
        }
        if !extra.is_empty() {
            create.truncate(create.len() - 2); // "\n)"
            create.push_str(&format!(",\n{}\n)", extra.join(",\n")));
        }

        let kept: Vec<(&Column, &Column)> = o
            .columns
            .iter()
            .filter_map(|oc| self.column(oc.id).map(|nc| (oc, nc)))
            .collect();
        let mut body = vec![create];
        if !kept.is_empty() {
            body.push(format!(
                "INSERT INTO {tmp} ({}) SELECT {} FROM {old}",
                kept.iter()
                    .map(|(_, n)| self.q(&n.name))
                    .collect::<Vec<_>>()
                    .join(", "),
                kept.iter()
                    .map(|(o, _)| self.q(&o.name))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        body.push(format!("DROP TABLE {old}"));
        body.push(format!("ALTER TABLE {tmp} RENAME TO {}", self.q(&t.name)));
        let table = self.qualified(&t.name);
        for i in t.indexes.iter().filter(|i| !self.unique_constraint(i)) {
            body.push(self.create_index(i, &table));
        }
        Plan {
            pre: vec!["PRAGMA foreign_keys = OFF".into()],
            body,
            check: Some("PRAGMA foreign_key_check".into()),
            post: vec!["PRAGMA foreign_keys = ON".into()],
            warnings: vec![
                "SQLite cannot make this change in place, so the table is rebuilt: \
                 its rows are copied into a new table that replaces it. Triggers on the \
                 table are dropped, and CHECK constraints, AUTOINCREMENT and \
                 foreign-key actions are not carried over."
                    .into(),
            ],
        }
    }
}

fn touches_retyped_ids(retyped: &BTreeSet<u64>, ids: &[u64]) -> bool {
    ids.iter().any(|c| retyped.contains(c))
}

/// `DROP TABLE`, optionally with `CASCADE` (Postgres).
pub fn drop_table(engine: Engine, schema: &str, table: &str, cascade: bool) -> String {
    let name = qualified_name(engine, Some(schema), table);
    if cascade && engine == Engine::Postgres {
        format!("DROP TABLE {name} CASCADE")
    } else {
        format!("DROP TABLE {name}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, ty: &str, nullable: bool, default: Option<&str>, pk: bool) -> ColumnInfo {
        ColumnInfo {
            name: name.into(),
            ordinal: 0,
            data_type: ty.into(),
            nullable,
            default: default.map(String::from),
            primary_key: pk,
        }
    }

    fn idx(name: &str, cols: &[&str], unique: bool, primary: bool, constraint: bool) -> IndexInfo {
        IndexInfo {
            name: name.into(),
            columns: cols.iter().map(|c| c.to_string()).collect(),
            unique,
            primary,
            constraint,
        }
    }

    fn orders(engine: Engine) -> Design {
        let grant = [TableGrant {
            grantee: "reporting".into(),
            privilege: "SELECT".into(),
            grantable: false,
        }];
        let schema = match engine {
            Engine::Postgres => "sales",
            Engine::Mssql => "dbo",
            Engine::Sqlite => "main",
        };
        Design::from_catalog(
            engine,
            schema,
            "orders",
            &[
                col("id", "integer", false, None, true),
                col("customer", "text", true, None, false),
                col("total", "numeric(10,2)", false, Some("0"), false),
            ],
            &[
                idx("orders_pkey", &["id"], true, true, true),
                idx("ix_customer", &["customer"], false, false, false),
            ],
            Vec::new(),
            if engine == Engine::Sqlite {
                &[]
            } else {
                &grant
            },
        )
    }

    fn body(d: &Design) -> Vec<String> {
        d.plan().unwrap().body
    }

    #[test]
    fn loaded_table_has_no_changes() {
        for e in Engine::ALL {
            let d = orders(e);
            assert!(d.plan().unwrap().is_empty(), "{e:?}");
            assert_eq!(d.table.primary_key.columns, vec![1]);
            assert_eq!(d.table.indexes.len(), 1);
        }
    }

    #[test]
    fn new_table_script() {
        let mut d = Design::new_table(Engine::Postgres, Some("sales"));
        d.table.name = "Customers".into();
        let name = d.add_column();
        d.column_mut(name).unwrap().name = "name".into();
        d.column_mut(name).unwrap().default = "''".into();
        let ix = d.add_index();
        d.index_mut(ix).unwrap().parts = vec![IndexPart::Column(name)];
        d.index_mut(ix).unwrap().unique = true;
        d.set_grant("reporting", "SELECT", true);
        assert_eq!(
            body(&d),
            vec![
                "CREATE TABLE sales.\"Customers\" (\n    id integer NOT NULL,\n    \
                 name text DEFAULT '',\n    PRIMARY KEY (id)\n)",
                "CREATE UNIQUE INDEX \"ix_Customers_1\" ON sales.\"Customers\" (name)",
                "GRANT SELECT ON sales.\"Customers\" TO reporting",
            ]
        );

        let mut d = Design::new_table(Engine::Mssql, None);
        d.table.name = "t".into();
        d.table.primary_key.name = "pk_t".into();
        d.add_column();
        assert_eq!(
            body(&d),
            vec![
                "CREATE TABLE [dbo].[t] (\n    [id] int NOT NULL,\n    \
                 [column2] nvarchar(255) NULL,\n    CONSTRAINT [pk_t] PRIMARY KEY ([id])\n)"
            ]
        );
    }

    #[test]
    fn problems_block_the_plan() {
        let mut d = Design::new_table(Engine::Sqlite, None);
        let c = d.add_column();
        d.column_mut(c).unwrap().name = "ID".into();
        d.add_index();
        let p = d.plan().unwrap_err();
        assert!(p.iter().any(|p| p.contains("needs a name")), "{p:?}");
        assert!(p.iter().any(|p| p.contains("twice")), "{p:?}");
        assert!(p.iter().any(|p| p.contains("no columns")), "{p:?}");
    }

    #[test]
    fn postgres_alter() {
        let mut d = orders(Engine::Postgres);
        d.table.name = "purchase".into();
        d.column_mut(2).unwrap().name = "client".into(); // rename
        d.column_mut(3).unwrap().data_type = "numeric(12,2)".into();
        d.column_mut(3).unwrap().default = String::new();
        let c = d.add_column();
        d.column_mut(c).unwrap().name = "note".into();
        d.index_mut(4).unwrap().unique = true; // changed → drop + create
        d.set_grant("reporting", "SELECT", false);
        d.set_grant("app", "INSERT", true);
        d.table.primary_key.name = "purchase_pkey".into();
        assert_eq!(
            body(&d),
            vec![
                "ALTER TABLE sales.orders RENAME TO purchase",
                "REVOKE SELECT ON sales.purchase FROM reporting",
                "DROP INDEX sales.ix_customer",
                "ALTER TABLE sales.purchase RENAME COLUMN customer TO client",
                "ALTER TABLE sales.purchase ALTER COLUMN total TYPE numeric(12,2) USING total::numeric(12,2)",
                "ALTER TABLE sales.purchase ALTER COLUMN total DROP DEFAULT",
                "ALTER TABLE sales.purchase ADD COLUMN note text",
                "ALTER TABLE sales.purchase RENAME CONSTRAINT orders_pkey TO purchase_pkey",
                "CREATE UNIQUE INDEX ix_customer ON sales.purchase (client)",
                "GRANT INSERT ON sales.purchase TO app",
            ]
        );
    }

    #[test]
    fn primary_key_change_drops_and_adds() {
        let mut d = orders(Engine::Postgres);
        d.toggle_pk(2);
        assert!(!d.column(2).unwrap().nullable, "key columns are NOT NULL");
        assert_eq!(
            body(&d),
            vec![
                "ALTER TABLE sales.orders DROP CONSTRAINT orders_pkey",
                "ALTER TABLE sales.orders ALTER COLUMN customer SET NOT NULL",
                "ALTER TABLE sales.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id, customer)",
            ]
        );
        d.revert();
        d.toggle_pk(1);
        assert_eq!(
            body(&d),
            vec!["ALTER TABLE sales.orders DROP CONSTRAINT orders_pkey"]
        );
    }

    #[test]
    fn removing_a_column_drops_its_index() {
        let mut d = orders(Engine::Postgres);
        d.remove_column(2);
        assert!(d.table.indexes.is_empty());
        assert_eq!(
            body(&d),
            vec![
                "DROP INDEX sales.ix_customer",
                "ALTER TABLE sales.orders DROP COLUMN customer",
            ]
        );
        d.restore_column(2);
        assert_eq!(d.table.columns[1].name, "customer");
    }

    #[test]
    fn mssql_alter_handles_defaults_and_indexes() {
        let mut d = orders(Engine::Mssql);
        d.column_mut(2).unwrap().data_type = "nvarchar(100)".into();
        d.column_mut(3).unwrap().default = "1".into();
        d.index_mut(4).unwrap().name = "ix_orders_customer".into(); // renamed, but column retyped
        let b = body(&d);
        assert_eq!(b[0], "DROP INDEX [ix_customer] ON [dbo].[orders]");
        assert!(b[1].starts_with("DECLARE @df sysname"), "{}", b[1]);
        assert!(b[1].contains("OBJECT_ID(N'[dbo].[orders]') AND c.name = N'total'"));
        assert_eq!(
            &b[2..],
            [
                "ALTER TABLE [dbo].[orders] ALTER COLUMN [customer] nvarchar(100) NULL",
                "ALTER TABLE [dbo].[orders] ADD DEFAULT 1 FOR [total]",
                "CREATE INDEX [ix_orders_customer] ON [dbo].[orders] ([customer])",
            ]
        );

        let mut d = orders(Engine::Mssql);
        d.table.name = "o2".into();
        d.column_mut(2).unwrap().name = "who".into();
        d.index_mut(4).unwrap().name = "ix_who".into();
        assert_eq!(
            body(&d),
            vec![
                "EXEC sp_rename N'[dbo].[orders]', N'o2'",
                "EXEC sp_rename N'[dbo].[o2].[customer]', N'who', N'COLUMN'",
                "EXEC sp_rename N'[dbo].[o2].[ix_customer]', N'ix_who', N'INDEX'",
            ]
        );
    }

    #[test]
    fn unique_constraints_stay_constraints() {
        let mut d = Design::from_catalog(
            Engine::Postgres,
            "public",
            "t",
            &[col("a", "int", false, None, false)],
            &[idx("t_a_key", &["a"], true, false, true)],
            Vec::new(),
            &[],
        );
        d.table.indexes[0].name = "t_a_uq".into();
        assert_eq!(
            body(&d),
            vec!["ALTER INDEX public.t_a_key RENAME TO t_a_uq"]
        );
        d.table.indexes[0].unique = false;
        assert_eq!(
            body(&d),
            vec![
                "ALTER TABLE public.t DROP CONSTRAINT t_a_key",
                "CREATE INDEX t_a_uq ON public.t (a)",
            ]
        );
    }

    #[test]
    fn sqlite_simple_changes_alter_in_place() {
        let mut d = orders(Engine::Sqlite);
        d.column_mut(2).unwrap().name = "client".into();
        let c = d.add_column();
        d.column_mut(c).unwrap().name = "note".into();
        d.column_mut(c).unwrap().default = "'x'".into();
        d.index_mut(4).unwrap().name = "ix_client".into();
        let p = d.plan().unwrap();
        assert!(p.pre.is_empty());
        assert_eq!(
            p.body,
            vec![
                "DROP INDEX ix_customer",
                "ALTER TABLE orders RENAME COLUMN customer TO client",
                "ALTER TABLE orders ADD COLUMN note TEXT DEFAULT 'x'",
                "CREATE INDEX ix_client ON orders (client)",
            ]
        );
    }

    #[test]
    fn sqlite_type_change_rebuilds() {
        let mut d = Design::from_catalog(
            Engine::Sqlite,
            "main",
            "items",
            &[
                col("id", "INTEGER", false, None, true),
                col("owner", "INTEGER", true, None, false),
                col("label", "TEXT", true, Some("datetime('now')"), false),
            ],
            &[
                idx("sqlite_autoindex_items_1", &["label"], true, false, true),
                idx("ix_owner", &["owner"], false, false, false),
            ],
            vec![ForeignKeyInfo {
                name: "fk_items_0".into(),
                columns: vec!["owner".into()],
                ref_schema: None,
                ref_table: "people".into(),
                ref_columns: vec!["id".into()],
            }],
            &[],
        );
        d.column_mut(3).unwrap().nullable = false;
        d.column_mut(3).unwrap().name = "title".into();
        let p = d.plan().unwrap();
        assert_eq!(p.pre, vec!["PRAGMA foreign_keys = OFF"]);
        assert_eq!(p.check.as_deref(), Some("PRAGMA foreign_key_check"));
        assert_eq!(
            p.body,
            vec![
                "CREATE TABLE _sqail_new_items (\n    id INTEGER NOT NULL,\n    owner INTEGER,\n    \
                 title TEXT NOT NULL DEFAULT (datetime('now')),\n    PRIMARY KEY (id),\n    \
                 UNIQUE (title),\n    FOREIGN KEY (owner) REFERENCES people (id)\n)",
                "INSERT INTO _sqail_new_items (id, owner, title) SELECT id, owner, label FROM items",
                "DROP TABLE items",
                "ALTER TABLE _sqail_new_items RENAME TO items",
                "CREATE INDEX ix_owner ON items (owner)",
            ]
        );
        assert!(!p.warnings.is_empty());
    }

    #[test]
    fn index_parts_keep_expressions() {
        let d = Design::from_catalog(
            Engine::Postgres,
            "public",
            "t",
            &[col("Name", "text", true, None, false)],
            &[idx(
                "ix",
                &["\"Name\"", "lower(\"Name\")"],
                false,
                false,
                false,
            )],
            Vec::new(),
            &[],
        );
        assert_eq!(
            d.table.indexes[0].parts,
            vec![
                IndexPart::Column(1),
                IndexPart::Expr("lower(\"Name\")".into())
            ]
        );
    }

    #[test]
    fn grants_with_grant_option_revoke_with_cascade() {
        let mut d = Design::from_catalog(
            Engine::Postgres,
            "public",
            "t",
            &[col("a", "int", true, None, false)],
            &[],
            Vec::new(),
            &[
                TableGrant {
                    grantee: "PUBLIC".into(),
                    privilege: "SELECT".into(),
                    grantable: false,
                },
                TableGrant {
                    grantee: "lead".into(),
                    privilege: "UPDATE".into(),
                    grantable: true,
                },
            ],
        );
        d.revoke_all("PUBLIC");
        d.revoke_all("lead");
        assert_eq!(
            body(&d),
            vec![
                "REVOKE SELECT ON public.t FROM PUBLIC",
                "REVOKE UPDATE ON public.t FROM lead CASCADE",
            ]
        );
    }

    #[test]
    fn drop_statements() {
        assert_eq!(
            drop_table(Engine::Postgres, "sales", "orders", true),
            "DROP TABLE sales.orders CASCADE"
        );
        assert_eq!(
            drop_table(Engine::Mssql, "dbo", "orders", true),
            "DROP TABLE [dbo].[orders]"
        );
        assert_eq!(
            drop_table(Engine::Sqlite, "main", "orders", false),
            "DROP TABLE orders"
        );
    }

    #[test]
    fn script_wraps_the_transaction() {
        let mut d = orders(Engine::Mssql);
        d.remove_column(2);
        let s = d.plan().unwrap().script(Engine::Mssql);
        assert!(s.starts_with("BEGIN TRANSACTION;\n"), "{s}");
        assert!(s.ends_with("COMMIT;"), "{s}");
    }
}
