#!/usr/bin/env bash
#===============================================================================
# SQaiL — Build release binaries with versioned filenames
#===============================================================================
# Builds Tauri binaries for the current platform, renames outputs to include
# the version and build number: sqail_<version>_<buildnr>_<platform>.<ext>
#
# Usage:
#   ./scripts/build-release.sh                   # build for current platform
#   ./scripts/build-release.sh --upload          # build + upload to VPS
#   ./scripts/build-release.sh --skip-build      # just collect existing artifacts
#   TARGETS="deb rpm" ./scripts/build-release.sh # build only specific bundle types
#
# Supported TARGETS (space-separated):
#   Linux:   deb rpm appimage   (default: deb rpm)
#   macOS:   dmg app            (default: dmg)
#   Windows: nsis msi           (default: nsis msi)
#
# The build number is generated by build-number.sh (yyyymmdd-revision format).
# Outputs go to dist/releases/
#===============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

# ── Parse flags ────────────────────────────────────────────────────────────
UPLOAD=false
SKIP_BUILD=false
for arg in "$@"; do
  case "$arg" in
    --upload) UPLOAD=true ;;
    --skip-build) SKIP_BUILD=true ;;
  esac
done

# ── Read version and build number ──────────────────────────────────────────
APP_VERSION=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' package.json | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
BUILD_NUMBER=$("$PROJECT_ROOT/scripts/build-number.sh")

echo "=== Building sqail v${APP_VERSION} (build ${BUILD_NUMBER}) ==="

# ── Detect platform ────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux" ;;
  Darwin*) PLATFORM="macos" ;;
  MINGW*|MSYS*|CYGWIN*) PLATFORM="windows" ;;
  *) echo "Unsupported OS: $OS"; exit 1 ;;
esac

echo "Platform: $PLATFORM"

# ── Determine bundle targets ──────────────────────────────────────────────
if [ -z "${TARGETS:-}" ]; then
  case "$PLATFORM" in
    linux)   TARGETS="deb rpm" ;;
    macos)   TARGETS="dmg" ;;
    windows) TARGETS="nsis msi" ;;
  esac
fi
echo "Bundle targets: $TARGETS"

# ── Prerequisites ──────────────────────────────────────────────────────────
command -v cargo >/dev/null 2>&1 || { echo "Error: Rust/Cargo not found."; exit 1; }
command -v pnpm  >/dev/null 2>&1 || { echo "Error: pnpm not found."; exit 1; }

# ── Build ──────────────────────────────────────────────────────────────────
if [ "$SKIP_BUILD" = false ]; then
  echo "Installing frontend dependencies..."
  pnpm install --frozen-lockfile

  echo "Building release..."
  # Build each target individually so one failure doesn't block the rest
  for target in $TARGETS; do
    echo "  Building bundle: $target ..."
    if pnpm tauri build --bundles "$target" 2>&1; then
      echo "  ✓ $target built successfully"
    else
      echo "  ✗ $target failed (continuing with remaining targets)"
    fi
  done
fi

# ── Collect & rename outputs ───────────────────────────────────────────────
BUNDLE_DIR="$PROJECT_ROOT/src-tauri/target/release/bundle"
RELEASE_DIR="$PROJECT_ROOT/dist/releases"
mkdir -p "$RELEASE_DIR"

PREFIX="sqail_${APP_VERSION}_${BUILD_NUMBER}"
COLLECTED=0

copy_artifact() {
  local src="$1"
  local dest_name="$2"
  if [ -f "$src" ]; then
    cp "$src" "$RELEASE_DIR/$dest_name"
    echo "  -> $dest_name ($(du -h "$RELEASE_DIR/$dest_name" | cut -f1))"
    COLLECTED=$((COLLECTED + 1))
  fi
}

echo ""
echo "Collecting artifacts..."

case "$PLATFORM" in
  linux)
    for f in "$BUNDLE_DIR/appimage/"*.AppImage 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_amd64.AppImage"
    done
    for f in "$BUNDLE_DIR/deb/"*.deb 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_amd64.deb"
    done
    for f in "$BUNDLE_DIR/rpm/"*.rpm 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_amd64.rpm"
    done
    ;;
  macos)
    # Detect host arch — a plain `tauri build` without --target produces a
    # host-arch binary. CI is the source of truth for the `_universal.dmg`
    # uploaded to sqail.io; this local path is for dev/testing.
    case "$(uname -m)" in
      arm64|aarch64) MAC_ARCH="aarch64" ;;
      x86_64)        MAC_ARCH="x64" ;;
      *)             MAC_ARCH="$(uname -m)" ;;
    esac
    # Ad-hoc sign the .app so the binary is at least runnable on arm64.
    # Does not fix Gatekeeper quarantine — users still need `xattr -cr`.
    for app in "$BUNDLE_DIR/macos/"*.app; do
      [ -d "$app" ] || continue
      codesign --force --deep --sign - "$app" 2>/dev/null || true
    done
    for f in "$BUNDLE_DIR/dmg/"*.dmg 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_${MAC_ARCH}.dmg"
    done
    for f in "$BUNDLE_DIR/macos/"*.app; do
      if [ -d "$f" ]; then
        tar -czf "$RELEASE_DIR/${PREFIX}_${MAC_ARCH}.app.tar.gz" -C "$BUNDLE_DIR/macos" "$(basename "$f")"
        echo "  -> ${PREFIX}_${MAC_ARCH}.app.tar.gz"
        COLLECTED=$((COLLECTED + 1))
      fi
    done
    ;;
  windows)
    for f in "$BUNDLE_DIR/nsis/"*.exe 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_x64-setup.exe"
    done
    for f in "$BUNDLE_DIR/msi/"*.msi 2>/dev/null; do
      [ -f "$f" ] && copy_artifact "$f" "${PREFIX}_x64-setup.msi"
    done
    ;;
esac

if [ "$COLLECTED" -eq 0 ]; then
  echo ""
  echo "WARNING: No artifacts collected. Check build output above for errors."
  exit 1
fi

# ── Generate releases manifest ────────────────────────────────────────────
MANIFEST="$RELEASE_DIR/manifest.json"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

FILES_JSON="["
FIRST=true
for f in "$RELEASE_DIR"/sqail_*; do
  [ -f "$f" ] || continue
  FNAME=$(basename "$f")
  if [ "$FIRST" = true ]; then
    FIRST=false
  else
    FILES_JSON+=","
  fi
  FILES_JSON+="\"$FNAME\""
done
FILES_JSON+="]"

cat > "$MANIFEST" <<EOF
{
  "version": "$APP_VERSION",
  "buildNumber": "$BUILD_NUMBER",
  "timestamp": "$TIMESTAMP",
  "files": $FILES_JSON
}
EOF

echo ""
echo "=== Build complete ($COLLECTED artifacts) ==="
echo "Release dir: $RELEASE_DIR"
ls -lh "$RELEASE_DIR"/sqail_* 2>/dev/null || true

# ── Optional: upload to VPS ────────────────────────────────────────────────
if [ "$UPLOAD" = true ]; then
  VPS_IP="${VPS_IP:-212.47.77.32}"
  VPS_USER="${VPS_USER:-bart}"
  REMOTE_DIR="/opt/sqail-releases"

  echo ""
  echo "Uploading to $VPS_USER@$VPS_IP:$REMOTE_DIR ..."
  ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" "sudo mkdir -p $REMOTE_DIR && sudo chown $VPS_USER:$VPS_USER $REMOTE_DIR"
  scp -o StrictHostKeyChecking=accept-new "$RELEASE_DIR"/sqail_* "$VPS_USER@$VPS_IP:$REMOTE_DIR/"
  scp -o StrictHostKeyChecking=accept-new "$MANIFEST" "$VPS_USER@$VPS_IP:$REMOTE_DIR/"
  echo "Upload complete."
fi
